name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: chmod u+x ./ruler.sh

    - name: Run
      run: bash ./ruler.sh

defaults:
  run:
    shell: bash
    working-directory: .
